export const natLangToCode = new Map<string, string>([
  ['Afrikaans', 'af'],
  ['Arabic (UAE)', 'ar-AE'],
  ['Arabic (Bahrain)', 'ar-BH'],
  ['Arabic (Algeria)', 'ar-DZ'],
  ['Arabic (Egypt)', 'ar-EG'],
  ['Arabic (Iraq)', 'ar-IQ'],
  ['Arabic (Jordan)', 'ar-JO'],
  ['Arabic (Kuwait)', 'ar-KW'],
  ['Arabic (Lebanon)', 'ar-LB'],
  ['Arabic (Lybia)', 'ar-LY'],
  ['Arabic (Morocco)', 'ar-MA'],
  ['Arabic (Oman)', 'ar-OM'],
  ['Arabic (Qatar)', 'ar-QA'],
  ['Arabic (Saudi Arabia)', 'ar-SA'],
  ['Arabic (Tunisia)', 'ar-TN'],
  ['Arabic (Yemen)', 'ar-YE'],
  ['Bulgarian', 'bg'],
  ['Catalan', 'ca'],
  ['Czech', 'cs'],
  ['German', 'de-DE'],
  ['Greek', 'el-GR'],
  ['English (Australia)', 'en-AU'],
  ['English (Canada)', 'en-CA'],
  ['English (UK)', 'en-GB'],
  ['English (New Zealand)', 'en-NZ'],
  ['English (US)', 'en-US'],
  ['English (South Africa)', 'en-ZA'],
  ['Spanish (Argentina)', 'es-AR'],
  ['Spanish (Bolivia)', 'es-BO'],
  ['Spanish (Chile)', 'es-CL'],
  ['Spanish (Colombia)', 'es-CO'],
  ['Spanish (Costa Rica)', 'es-CR'],
  ['Spanish (Dominican Republic)', 'es-DO'],
  ['Spanish (Ecuador)', 'es-EC'],
  ['Spanish (Spain)', 'es-ES'],
  ['Spanish (Guatemala)', 'es-GT'],
  ['Spanish (Honduras)', 'es-HN'],
  ['Spanish (Mexico)', 'es-MX'],
  ['Spanish (Nicaragua)', 'es-NI'],
  ['Spanish (Panama)', 'es-PA'],
  ['Spanish (Peru)', 'es-PE'],
  ['Spanish (Puerto Rico)', 'es-PR'],
  ['Spanish (Paraguay)', 'es-PY'],
  ['Spanish (El Salvador)', 'es-SV'],
  ['Spanish (Uruguay)', 'es-UY'],
  ['Spanish (Venezuela)', 'es-VE'],
  ['Basque', 'eu'],
  ['Finnish', 'fi'],
  ['French', 'fr-FR'],
  ['Galician', 'gl'],
  ['Hebrew', 'he'],
  ['Hungarian', 'hu'],
  ["Hindi", "hi-IN"],
  ['Indonesian', 'id'],
  ['Icelandic', 'is'],
  ['Italian', 'it-IT'],
  ['Japanese', 'ja'],
  ['Korean', 'ko'],
  ['Malaysian', 'ms-MY'],
  ['Dutch', 'nl-NL'],
  ['Polish', 'pl'],
  ['Portuguese', 'pt-PT'],
  ['Romanian', 'ro-RO'],
  ['Russian', 'ru'],
  ['Slovak', 'sk'],
  ['Serbian', 'sr-SP'],
  ['Swedish', 'sv-SE'],
  ['Turkish', 'tr'],
  ['Mandarin Chinese', 'zh-CN'],
  ['Cantonese', 'zh-HK'],
  ['Taiwanese', 'zh-TW'],
  ['Zulu', 'zu']
]);


export const codeToEngLang = new Map<string, string>([
  ['af', 'Afrikaans'],
  ['ar-AE', 'Arabic (UAE)'],
  ['ar-BH', 'Arabic (Bahrain)'],
  ['ar-DZ', 'Arabic (Algeria)'],
  ['ar-EG', 'Arabic (Egypt)'],
  ['ar-IQ', 'Arabic (Iraq)'],
  ['ar-JO', 'Arabic (Jordan)'],
  ['ar-KW', 'Arabic (Kuwait)'],
  ['ar-LB', 'Arabic (Lebanon)'],
  ['ar-LY', 'Arabic (Lybia)'],
  ['ar-MA', 'Arabic (Morocco)'],
  ['ar-OM', 'Arabic (Oman)'],
  ['ar-QA', 'Arabic (Qatar)'],
  ['ar-SA', 'Arabic (Saudi Arabia)'],
  ['ar-TN', 'Arabic (Tunisia)'],
  ['ar-YE', 'Arabic (Yemen)'],
  ['bg', 'Bulgarian'],
  ['ca', 'Catalan'],
  ['cs', 'Czech'],
  ['de-DE', 'German'],
  ['el-GR', 'Greek'],
  ['en-AU', 'English (Australia)'],
  ['en-CA', 'English (Canada)'],
  ['en-GB', 'English (UK)'],
  ['en-NZ', 'English (New Zealand)'],
  ['en-US', 'English (US)'],
  ['en-ZA', 'English (South Africa)'],
  ['es-AR', 'Spanish (Argentina)'],
  ['es-BO', 'Spanish (Bolivia)'],
  ['es-CL', 'Spanish (Chile)'],
  ['es-CO', 'Spanish (Colombia)'],
  ['es-CR', 'Spanish (Costa Rica)'],
  ['es-DO', 'Spanish (Dominican Republic)'],
  ['es-EC', 'Spanish (Ecuador)'],
  ['es-ES', 'Spanish (Spain)'],
  ['es-GT', 'Spanish (Guatemala)'],
  ['es-HN', 'Spanish (Honduras)'],
  ['es-MX', 'Spanish (Mexico)'],
  ['es-NI', 'Spanish (Nicaragua)'],
  ['es-PA', 'Spanish (Panama)'],
  ['es-PE', 'Spanish (Peru)'],
  ['es-PR', 'Spanish (Puerto Rico)'],
  ['es-PY', 'Spanish (Paraguay)'],
  ['es-SV', 'Spanish (El Salvador)'],
  ['es-UY', 'Spanish (Uruguay)'],
  ['es-VE', 'Spanish (Venezuela)'],
  ['eu', 'Basque'],
  ['fi', 'Finnish'],
  ['fr-FR', 'French'],
  ['gl', 'Galician'],
  ['he', 'Hebrew'],
  ['hu', 'Hungarian'],
  ["hi-IN", "Hindi"],
  ['id', 'Indonesian'],
  ['is', 'Icelandic'],
  ['it-IT', 'Italian'],
  ['ja', 'Japanese'],
  ['ko', 'Korean'],
  ['ms-MY', 'Malaysian'],
  ['nl-NL', 'Dutch'],
  ['pl', 'Polish'],
  ['pt-PT', 'Portuguese'],
  ['ro-RO', 'Romanian'],
  ['ru', 'Russian'],
  ['sk', 'Slovak'],
  ['sr-SP', 'Serbian'],
  ['sv-SE', 'Swedish'],
  ['tr', 'Turkish'],
  ['zh-CN', 'Mandarin Chinese'],
  ['zh-HK', 'Cantonese'],
  ['zh-TW', 'Taiwanese'],
  ['zu', 'Zulu']  
]);


// export const natLangToCode = new Map<string, string>([
//   ["Deutsch", "de-DE"],
//   ["US English", "en-US"],
//   ["UK English", "en-GB"],
//   ["Español", "es-ES"],
//   ["Español de Estados Unidos", "es-US"],
//   ["Français", "fr-FR"],
//   ["हिन्दी Hind", "hi-IN"],
//   ["Bahasa Indonesia", "id-ID"],
//   ["Italiano", "it-IT"],
//   ["日本語", "ja-JP"],
//   ["한국의", "ko-KR"],
//   ["Nederlands", "nl-NL"],
//   ["Polski", "pl-PL"],
//   ["Português do Brasil", "pt-BR"],
//   ["Pусский", "ru-RU"],
//   ["普通话（中国大陆）", "zh-CN"],
//   ["粤語（香港）", "zh-HK"],
//   ["國語（臺灣）", "zh-TW"]
// ]);


// export const codeToEngLang = new Map<string, string>([
//   ["de-DE", "German"],
//   ["en-US", "English"],
//   ["en-GB", "English"],
//   ["es-ES", "Spanish"],
//   ["es-US", "Spanish"],
//   ["fr-FR", "French"],
//   ["hi-IN", "Hindi"],
//   ["id-ID", "Indonesian"],
//   ["it-IT", "Italian"],
//   ["ja-JP", "Japanese"],
//   ["ko-KR", "Korean"],
//   ["nl-NL", "Dutch"],
//   ["pl-PL", "Polish"],
//   ["pt-BR", "Portugese"],
//   ["ru-RU", "Russian"],
//   ["zh-CN", "Chinese"],
//   ["zh-HK", "Chinese"],
//   ["zh-TW", "Chinese"]
// ]);


